In [2]:
import os
os.chdir(r"G:\PycharmProjects\names-demo")

In [ ]:
import pandas as pd
import os
import polars as pl
# folder containing your files
folder_path = "data/raw/names-usa/namesbystate"

# list all files (adjust extension if needed)
files = [f for f in os.listdir(folder_path) if f.endswith(".TXT")]

df_list = []

for file in files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path,header=None,names=["state", "gender", "year", "name", "count"])
    df_list.append(df)

# combine all files into one dataframe
df = pd.concat(df_list, ignore_index=True)
df.head()

In [ ]:
state_map = {
    'AK': 'Alaska', 'AL': 'Alabama', 'AR': 'Arkansas', 'AZ': 'Arizona',
    'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut',
    'DC': 'District of Columbia', 'DE': 'Delaware', 'FL': 'Florida',
    'GA': 'Georgia', 'HI': 'Hawaii', 'IA': 'Iowa', 'ID': 'Idaho',
    'IL': 'Illinois', 'IN': 'Indiana', 'KS': 'Kansas', 'KY': 'Kentucky',
    'LA': 'Louisiana', 'MA': 'Massachusetts', 'MD': 'Maryland',
    'ME': 'Maine', 'MI': 'Michigan', 'MN': 'Minnesota',
    'MO': 'Missouri', 'MS': 'Mississippi', 'MT': 'Montana',
    'NC': 'North Carolina', 'ND': 'North Dakota', 'NE': 'Nebraska',
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico',
    'NV': 'Nevada', 'NY': 'New York', 'OH': 'Ohio', 'OK': 'Oklahoma',
    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island',
    'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee',
    'TX': 'Texas', 'UT': 'Utah', 'VA': 'Virginia', 'VT': 'Vermont',
    'WA': 'Washington', 'WI': 'Wisconsin', 'WV': 'West Virginia',
    'WY': 'Wyoming'
}
df["state"] = df["state"].map(state_map)
# 'sex' sütunundaki değerleri yeni değerlerle eşleyelim
df.head()

In [ ]:
# Rename gender labels
df['gender'] = df['gender'].map({'F': 'female', 'M': 'male'})
# Generate gender based total counts
df['total_count'] = df.groupby(['state','gender', 'year'])['count'].transform('sum')
df.head()

In [49]:
# Create rank column
df['rank'] = df.groupby(['year', 'gender','state'])['count'].rank(ascending=False, method='min').astype(int)

# Sonuçları 'count' ve 'rank' sütunlarına göre sıralayarak kontrol edelim
df = df.sort_values(by=['year', 'gender', 'rank'])

In [50]:
df[(df["year"]==2024) & (df["gender"]=="female")].head(44)

,state,gender,year,name,count,total_count,rank
15509,Alaska,female,2024,Amelia,39,1652,1
108002,Alabama,female,2024,Charlotte,234,18655,1
233794,Arkansas,female,2024,Olivia,132,10489,1
356580,Arizona,female,2024,Olivia,346,27906,1
657438,California,female,2024,Mia,1986,164782,1
899467,Colorado,female,2024,Olivia,277,22644,1
1002341,Connecticut,female,2024,Mia,167,11353,1
1002342,Connecticut,female,2024,Olivia,167,11353,1
1072736,District of Columbia,female,2024,Charlotte,48,2271,1
1119189,Delaware,female,2024,Charlotte,46,2085,1
1264087,Florida,female,2024,Olivia,1142,86003,1
1476387,Georgia,female,2024,Charlotte,451,45331,1
1476388,Georgia,female,2024,Olivia,451,45331,1
1599249,Hawaii,female,2024,Olivia,40,2223,1
1681952,Iowa,female,2024,Charlotte,140,11555,1
1760673,Idaho,female,2024,Charlotte,95,6884,1
1931197,Illinois,female,2024,Olivia,501,44808,1
2123351,Indiana,female,2024,Charlotte,354,28052,1
2245924,Kansas,female,2024,Charlotte,166,11472,1
2362143,Kentucky,female,2024,Charlotte,204,17357,1
2504991,Louisiana,female,2024,Olivia,204,16924,1
2653133,Massachusetts,female,2024,Olivia,339,24068,1
2776838,Maryland,female,2024,Olivia,231,20743,1
2860737,Maine,female,2024,Charlotte,60,2983,1
2996180,Michigan,female,2024,Charlotte,382,35612,1
3152085,Minnesota,female,2024,Charlotte,225,21269,1
3291396,Missouri,female,2024,Amelia,292,23638,1
3291397,Missouri,female,2024,Charlotte,292,23638,1
3423250,Mississippi,female,2024,Ava,94,8884,1
3505417,Montana,female,2024,Lainey,47,2823,1
3631407,North Carolina,female,2024,Olivia,469,46021,1
3745629,North Dakota,female,2024,Evelyn,48,2561,1
3810812,Nebraska,female,2024,Charlotte,107,7449,1
3870210,New Hampshire,female,2024,Charlotte,93,3677,1
3982705,New Jersey,female,2024,Mia,468,36227,1
4098889,New Mexico,female,2024,Mia,81,4901,1
4165278,Nevada,female,2024,Olivia,159,8944,1
4372634,New York,female,2024,Mia,836,78286,1
4635462,Ohio,female,2024,Charlotte,531,46592,1
4796829,Oklahoma,female,2024,Olivia,165,14533,1
4907260,Oregon,female,2024,Olivia,164,13059,1
5073403,Pennsylvania,female,2024,Olivia,513,46170,1
5191267,Rhode Island,female,2024,Charlotte,48,2410,1
5278033,South Carolina,female,2024,Charlotte,227,18157,1

In [51]:
# Save to Parquet
df.to_parquet("data/preprocessed/usa/names_usa_states.parquet", engine="pyarrow", index=False)

In [9]:
# Read the saved file for checking
# import polars as pl
df = pl.read_parquet("data/preprocessed/usa/names_usa_states.parquet")
df.head()

shape: (5, 6)
┌────────┬────────┬──────┬──────────┬───────┬─────────────┐
│ state  ┆ gender ┆ year ┆ name     ┆ count ┆ total_count │
│ ---    ┆ ---    ┆ ---  ┆ ---      ┆ ---   ┆ ---         │
│ str    ┆ str    ┆ i64  ┆ str      ┆ i64   ┆ i64         │
╞════════╪════════╪══════╪══════════╪═══════╪═════════════╡
│ Alaska ┆ female ┆ 1910 ┆ Mary     ┆ 14    ┆ 352089      │
│ Alaska ┆ female ┆ 1910 ┆ Annie    ┆ 12    ┆ 352089      │
│ Alaska ┆ female ┆ 1910 ┆ Anna     ┆ 10    ┆ 352089      │
│ Alaska ┆ female ┆ 1910 ┆ Margaret ┆ 8     ┆ 352089      │
│ Alaska ┆ female ┆ 1910 ┆ Helen    ┆ 7     ┆ 352089      │
└────────┴────────┴──────┴──────────┴───────┴─────────────┘

In [35]:
import geopandas as gpd

url = "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json"
gdf = gpd.read_file(url)[["name","geometry"]]
gdf.head()

         name                                           geometry
0     Alabama  POLYGON ((-87.3593 35.00118, -85.60668 34.9847...
1      Alaska  MULTIPOLYGON (((-131.60202 55.11798, -131.5691...
2     Arizona  POLYGON ((-109.0425 37.00026, -109.04798 31.33...
3    Arkansas  POLYGON ((-94.47384 36.50186, -90.15254 36.496...
4  California  POLYGON ((-123.23326 42.00619, -122.37885 42.0...

In [36]:
import geopandas as gpd
gdf.rename(columns={"name":"state"},inplace=True)
gdf.to_parquet("data/preprocessed/usa/usa_states_geo.parquet")

print(gdf.head())

        state                                           geometry
0     Alabama  POLYGON ((-87.3593 35.00118, -85.60668 34.9847...
1      Alaska  MULTIPOLYGON (((-131.60202 55.11798, -131.5691...
2     Arizona  POLYGON ((-109.0425 37.00026, -109.04798 31.33...
3    Arkansas  POLYGON ((-94.47384 36.50186, -90.15254 36.496...
4  California  POLYGON ((-123.23326 42.00619, -122.37885 42.0...

In [26]:
print(gdf.shape)

(50, 2)